### ISSUE TITLE
Rename repository to reflect clojure target?

### ISSUE THREAD

**Issue by tlaukkanen** [LiaisonTechnologies/arango-db-client#1]
Maybe to rename repository so it's clear to users what language it is meant to? _arangodb-clojure-driver_?
Like official drivers:
- https://github.com/arangodb/arangodb-java-driver (for Java)
- https://github.com/arangodb/arangojs (for JavaScript)

**Comment by manderson202** [comment]
Moving this issue to main dm issue repo.
